name: CI

on:
  push:
    tags:
      - '*'
jobs:
  main:
    uses: visibilityspots/github-workflows/.github/workflows/main.yml@main
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
